[package]
name = "fae"
version = "0.4.1-alpha.0"
authors = ["Jens Pitkanen <jens@neon.moe>"]
edition = "2018"
description = "A simple and fast 2D rendering crate with optional window creation and text rendering functionality."
readme = "README.md"
# Since the crate isn't ready for usage, don't set these just yet.
# keywords = ["graphics", "2d", "renderer", "sprite"]
# categories = ["rendering", "rendering::engine"]
license = "MIT"
repository = "https://github.com/neonmoe/fae"

[badges]
maintenance = { status = "experimental" }

[dependencies]
glutin = { version = "^0.21.1" }
png = { version = "^0.15.0", optional = true }
font8x8 = { version = "^0.2.5", optional = true, default_features = false, features = ["std"] }

[features]
default = ["text", "png", "font8x8", "profiler"]
text = []
profiler = []

[build-dependencies]
gl_generator = "^0.11.0"
