[package]
name = "fae"
version = "0.4.1-alpha.0"
authors = ["Jens Pitkanen <jens@neon.moe>"]
edition = "2018"
description = "A simple and fast 2D rendering crate with optional window creation and text rendering functionality."
readme = "README.md"
# Since the crate isn't ready for usage, don't set these just yet.
# keywords = ["graphics", "2d", "renderer", "sprite"]
# categories = ["rendering", "rendering::engine"]
license = "MIT"
repository = "https://github.com/neonmoe/fae"

[badges]
maintenance = { status = "experimental" }

[dependencies]
glutin = "^0.21.1"
log = "^0.4.8"
png = { version = "^0.15.0", optional = true }
font8x8 = { version = "^0.2.5", optional = true, default_features = false, features = ["std"] }
# This rusttype version is based on rusttype 0.7.9's deps, which is based on
# andrew's deps, which is pulled in by glutin on wayland. So, no duplicates.
rusttype = { version = "^0.8", optional = true }
lazy_static = { version = "^1.4.0", optional = true }

[features]
# FIXME: the `profiler` feature should not be default in releases
default = ["text", "png", "font8x8", "rusttype", "profiler"]
text = []
profiler = ["lazy_static"]

[dev-dependencies]
# Note: using a logger adds a lot of executable size.
env_logger = "^0.7.1"

[build-dependencies]
gl_generator = "^0.11.0"
